### ISSUE TITLE
Object.values(...)[0] is not a constructor

### ISSUE THREAD

**Issue by Youssif-Hany** [hemdan-dev/loopback4-seeders#1]
I tried to follow the instructions with new empty loopback project
but before I use the script `npm run build && npm run seed`
The App crashed after logging 

> Started to seeding data
(node:35852) UnhandledPromiseRejectionWarning: TypeError: Object.values(...)[0] is not a constructor at Loopback4Seeder.fetchApplication

I could not figure out the problem

**Comment by hemdan-dev** [comment]
You didn't seed the project with any seeders files, right?

**Comment by yhfa** [comment]
No, just added TestSeeder as the instructions told

**Comment by hemdan-dev** [comment]
Am tested with lb4 latest version and working well, can you elaborate about your steps before error
